replicaCount: 3

image:
  repository: apache/nifi
  tag: "2.4.0"
  pullPolicy: IfNotPresent

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 10Gi

auth:
  singleUser:
    username: "admin"
    password: "changemechangeme"

configFlow:
  enabled: true
  configMapName: basic-flow-json
  mountPath: /opt/nifi/flow

ingress:
  enabled: false

resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 1
    memory: 2Gi

service:
  type: ClusterIP
  port: 8080

configFlow:
  enabled: true
  flowJson: |-
    {
      "rootGroup": {}
    }
