{{- if .Values.configFlow.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configFlow.configMapName }}
data:
  basic-flow.json: |-
{{ .Values.configFlow.flowJson | indent 4 }}
{{- end }}