replicaCount: 1

image:
  repository: apache/nifi
  tag: "2.4.0"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8080

persistence:
  enabled: true
  size: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClass: "standard"

adminUser:
  username: admin
  password: admin123

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - nifi.local
  tls:
    - secretName: nifi-tls
      hosts:
        - nifi.local

metrics:
  enabled: true
